### ISSUE TITLE
loosing borders in selectize widget after pressing button "Reset to initial" in bootstrap mode

### ISSUE THREAD

**Issue by amikphoto** [jrief/django-formset#122]
I've a form with selectize widget (foreing key). When the form is opened I press on "Reset to initial" button this fiels loosing border and style. Is it bug?

**Comment by lsmoker** [comment]
I am also seeing an error when doing this. The SelectizeMultiple widget becomes inactive after clicking the Reset button. The console prints "Bad Request: my_url_path". The problem appears to be in formset/collection.py - https://github.com/jrief/django-formset/blob/0ec769546d6c241a4e10f29ef0caafe4d4b9e379/formset/collection.py#L490

**Comment by jrief** [comment]
Thanks for reporting. I'll have a look at this.

**Comment by jrief** [comment]
@amikphoto I just tested on the demo page. What I see here, after clicking "Reset to initial" the field named "Static Opinion" forgets about all its options. However, I do not see the field losing its borders. How can I reproduce this?

**Comment by jrief** [comment]
I now fixed the problem with Reset on the Selectize widget with "Static Opinion".

However, I am not able to reproduce the field losing its borders.

**Comment by amikphoto** [comment]
Thank you very much for your work!
But finally It seems to me the main problem of Selectize widget is in formset collections. 
When I try to use Selectize widget in form collection and when I start input letters for serach in the form I have the same problem as [Lsmoker ](https://github.com/jrief/django-formset/issues/122#issuecomment-2018645574). The same problem is when I press "Reset to initial". I can't say exactly but it seems to me the problem is the reason of loosing css style (borders).

**Comment by jrief** [comment]
> But finally It seems to me the main problem of Selectize widget is in formset collections.

This was the missing information. Now I am able to reproduce this myself.

**Comment by amikphoto** [comment]
> > But finally It seems to me the main problem of Selectize widget is in formset collections.
> 
> This was the missing information. Now I am able to reproduce this myself.
I'm sorry to disturd you but just ask :) Did you find the problem? Could I hope to use Selectize in collections soon?

**Comment by jrief** [comment]
> I'm sorry to disturd you but just ask :) Did you find the problem? Could I hope to use Selectize in collections soon?

I just pushed a working solution. I have to fix some unit tests before releasing a new version.

**Comment by amikphoto** [comment]
Thank you very much!

**Comment by amikphoto** [comment]
Still have the problem with new release 1.3.9. It happened when I use selectize widget and when I use active search in the widget and it tries to get answer from backend to get new list of options. 

The problem appears in:

class FormCollection(BaseFormCollection, metaclass=FormCollectionMeta):
    """
    Base class for a collection of forms. Attributes of this class which inherit from
    `django.forms.forms.BaseForm` are managed by this class.
    """
    def get_field(self, field_path):
        path = field_path.split('.', 1)
        key, path = path
        return self.declared_holders[key].get_field(path)

![image](https://github.com/jrief/django-formset/assets/36606543/c8ac07d4-4050-4859-afb1-7c3d3fe2ff9b)

self.declared_holders[key].get_field(path) return KeyError:'0'
