### ISSUE TITLE
DateRangePicker is off by one day

### ISSUE THREAD

**Issue by felixblanke** [jrief/django-formset#239]
Hi, when using the DateRangePicker, I run into the problem that the date range POSTed to the server are one day off from the range shown in the widget, i.e. selecting `2025-03-02 - 2025-03-03` in the widget results in `2025-03-01 - 2025-03-02` being sent to the server.

I could reproduce this behavior in the testing app "BookingPickerForm" as well as on the [docs page](https://django-formset.fly.dev/date-time-range/).

**Comment by jrief** [comment]
May I ask in which timezone you are and the approximate time you made the test? Unfortunately browsers do weired stuff with time zones.

**Comment by felixblanke** [comment]
Sure, `Europe/Berlin`, so I think UTC+2 at the moment. I ran the tests shortly before opening the issue, but I just now confirmed again on the docs page (16:30 2025-09-11)

**Comment by felixblanke** [comment]
In case it's relevant: I tested the docs page on Firefox and chrome, each on my Laptop as well as my Android phone

**Comment by jrief** [comment]
I really am unable to reproduce this. I always get the right result, even if my locale date is different from the UTC date. If you use the Chrome developer tools you can emulate the timezone. Maybe this helps me to reproduce the issue.

**Comment by jrief** [comment]
I found something myself now. Will inform you whenever there is a fix. Thanks for reporting.

**Comment by felixblanke** [comment]
Thank you for the remark on chrome dev tools, I didn't know that was possible. I just checked for different timezones. For UTC or anything behind UTC (like `America/San_Francisco` at UTC-7) I can't reproduce it. For anything before UTC (like `Europe/Berlin`) it does occur. So maybe there is some implicit conversion to UTC time before extracting the date?

**Comment by jrief** [comment]
I just fixed this. If you're able to compile the TypeScript sources, please test this in your environment. Otherwise please wait until I release version 2.1.2.
Again, thanks for reporting.

**Comment by felixblanke** [comment]
Thank you for the quick fixing! I just confirmed it for the datepicker testapp.

However, for the calendar widget the original bug still occurs for me. Should I open another issue for this?

**Comment by jrief** [comment]
Yes. Please do.

**Comment by jrief** [comment]
@felixblanke your last comment should be fixed now. Can you please retry.
